console.log('====================================');
console.log("Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:\n\nlet car = 'subaru';\n\nconsole.log(\"Is car == 'subaru'? I predict True.\")\n\nconsole.log(car == 'subaru')");
console.log("Author:[Muhammad Saif ur Rehman]");
var currentDate = new Date().toDateString();
console.log("Date:", currentDate);
console.log('====================================');
var car = 'subaru';
var age = 25;
var isRainyDay = true || false;
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is age >= 18? I predict True.");
console.log(age >= 18);
console.log("Is age < 21? I predict True.");
console.log(age < 21);
console.log("Is age === 25? I predict True.");
console.log(age === 25);
console.log("Is age !== 25? I predict False.");
console.log(age !== 25);
console.log("Is isRainyDay === true? I predict True.");
console.log(isRainyDay === true);
console.log("Is isRainyDay === false? I predict False.");
console.log(isRainyDay === false);
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru'); // Case-sensitive comparison
console.log("Is age > 30? I predict False.");
console.log(age > 30);
console.log("Is age <= 25? I predict True.");
console.log(age <= 25);
